
#r "Microsoft.ML.Api"
#r "Microsoft.ML.Core"
#r "Microsoft.ML.CpuMath"
#r "Microsoft.ML.Data"
#r "Microsoft.ML"
#r "Microsoft.ML.FastTree"
#r "Microsoft.ML.InternalStreams"
#r "Microsoft.ML.KMeansClustering"
#r "Microsoft.ML.Maml"
#r "Microsoft.ML.PCA"
#r "Microsoft.ML.PipelineInference"
#r "Microsoft.ML.ResultProcessor"
#r "Microsoft.ML.StandardLearners"
#r "Microsoft.ML.Sweeper"
#r "Microsoft.ML.Transforms"
#r "Microsoft.ML.UniversalModelFormat"